apiVersion: apps/v1
kind: Deployment
metadata:
  name: voteapp-deployment
  namespace: vote-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voteapp
  template:
    metadata:
      labels:
        app: voteapp
    spec:
      containers:
      - name: voteapp-container
        image: saikishore1903/k8s-kind-voting-app-vote:latest
        ports:
          - containerPort: 80